### ISSUE TITLE
No specified C++ standard in make files and potential issues

### ISSUE THREAD

**Issue by GiuseppeCesarano** [webui-dev/webui#103]
The make files responsible for compiling the C++ examples in the project currently lack a selected C++ standard, and there is no mention of the targeted C++ standard within the project.

This could lead to:  

1) Lack of feature awareness for contributors  
Contributors may face difficulties in determining which C++ language features are available to them. For instance, the current implementation of the `window::return_string` member function in the C++ bindings:  
```c++
void return_string(webui::event* e, std::string s) {
  webui_event_t* c_e = convert_event_to_webui_event(e);
  webui_return_string(c_e, &s[0]);
  delete c_e;
}
```
This demonstrates passing a string by value, which can be computationally expensive. However, in this particular case, such copying is unnecessary, as the function `webui_return_string` already creates a copy of the string. To mitigate this, there are two main approaches: passing the `std::string` as `const std::string&` or utilizing `std::string_view`. The latter is the recommended approach due to its ability to alias to various types and potentially avoid costly calls to the `std::string` constructor. Nevertheless, adopting `std::string_view` requires C++20, and implementing this change with the current make files will result in compilation errors.

2) Inconsistency across compilers  
By not explicitly defining the C++ standard, the compilers will resort to defaulting to a particular standard based on the compiler version. For instance, clang 15 will default to using C++14, while clang 16 will default to C++17. This inconsistency can lead to the infamous "it works on my PC" problem.

Additionally, considering the nature of the project and the potential benefits of modern C++ features, it is recommended to adopt at least C++20 as the targeted standard within the make files.

**Comment by hassandraga** [comment]
Thank you, Giuseppe, for pointing this out.

Honestly, this project is purely C99, but someone on Reddit requested a C++ wrapper, so I created the C++ wrapper in 20-25 minutes in a rush... and for sure, it's not complete and needs improvements.

You are right about the unnecessary strings copy, so I update it to use references instead of values, especially when APIs take `const char*`. So, thank you for reporting that.

About the standard, the WebUI C++ wrapper is relatively small and easy, so selecting a minimum standard as C++11 is enough. This helps developers who are using WebUI in old embedded/PC devices. On the other hand, anyone can easily modify the `webui.hpp` and `makefile` to set a different standard as needed.

Fix: https://github.com/webui-dev/webui/commit/cdf67b17ac65c6467733fbd0adcbfe17f084ac02

**Comment by GiuseppeCesarano** [comment]
This fixes the problem, so I'm closing the thread.

However, I want to point out that taking `const std::string&` as a parameter can be just as bad as taking `std::string` as a parameter, for example, in the worst case, if a string literal exceeding the length of 20 is passed to a function expecting a `const std::string&`, the std::string constructor is called and an allocation and copy occurs.

https://godbolt.org/z/n3vh9TzP7

**Comment by AlbertShown** [comment]
That's true, but unfortunately, this is the nature of C++.
`const std::string&` is the best option take take `std::string foo = "Hello"` or `"Hello"`. When you pass in an existing `std::string object`, there will be no copy or allocation, just a reference to the existing string. When you pass a string literal `const char*`, a temporary `std::string` object must be created (_Copy_).

The best solution is providing overloads for both `const char*` and `std::string` to handle both cases optimally.

**Comment by AlbertShown** [comment]
I already taught about using `const char*`, but as you said, it will make the user call `.c_str()`, making the code look strange!

Honestly, using `std::string_view` can be a good option in many cases, especially since we don't modify the string. Would you like please modify [webui.hpp](https://github.com/webui-dev/webui/blob/main/include/webui.hpp)? I will modify Makefiles to use the C++17 standard instead of C++11.

**Comment by GiuseppeCesarano** [comment]
I was already preparing a patch with some minor stuff. If you feel like doing the standard change I will add the string_view and wait for your commit.
