### ISSUE TITLE
Active wait could be avoided

### ISSUE THREAD

**Issue by GiuseppeCesarano** [webui-dev/webui#115]
A `conditional_variable` could be used to implement `webui_wait()` to avoid the active wait.

This is not really a performance issue, but it's odd to see a wait call [take more time](https://share.firefox.dev/3IJRT6N) than user functions.

Feel free to close the issue if the development time isn't worth the investment.

**Comment by hassandraga** [comment]
I'm not sure what you mean by `conditional_variable` to implement `webui_wait()`. But, for wrappers that do not want a sync wait method, they can use `webui_interface_is_app_running()` instead of waiting.

**Comment by GiuseppeCesarano** [comment]
`conditional_variable` is a class in the standard C++ library that is basically a wrapper around some `pthread` functionality; these primitives allow more threads to wait until a signal is sent by the owner of the variable. This would turn active waiting into passive waiting.

I'm linking to the [std::conditional_variable] documentation (https://en.cppreference.com/w/cpp/thread/condition_variable) just because it's simple and has a good example; of course we could use the C posix API. 

For the Windows counterpart, to be honest, I don't have any experience, we should do some research, but since the standard C++ implementation exists, I'm sure it won't be a problem.

**Comment by hassandraga** [comment]
Sorry, my bad. Because we are talking about `webui_wait()`, which is in C, I didn't think about C++ at all.

In general, the standard is cross-platform. The docs show an example using `std::condition_variable`, `std::unique_lock` and `std::thread`, which all should work fine in all OS.

But I still don't fully understand how you plan to implement this in WebUI. Can you please give me more details?

**Comment by GiuseppeCesarano** [comment]
I I guess I didn't explain myself well, what I meant is that we could use `pthread_cond_wait` instead of `sleep` to implement `webui_wait`.

The C++ link was only helpful in understanding how this would work

**Comment by AlbertShown** [comment]
Giuseppe is a C++ guy. Even talking about `pthread` in C, he still gives C++ examples 😂👍

**Comment by AlbertShown** [comment]
You are right @GiuseppeCesarano. WebUI has no mutex implementation yet, so that we can start with `pthread_cond_wait` for Linux and macOS, `WaitForMultipleObjects()` and `SleepConditionVariableCS()` for Windows.

We can also use the built-in C11 mutex, which is `thrd_create()`, `thrd_join()`, `mtx_lock()`, `mtx_unlock()`, `cnd_wait()`, `cnd_signal()`. But, this will make WebUI need a C11 compiler.

**Comment by hassandraga** [comment]
I just found some free time to implement it. Thank you @GiuseppeCesarano, for this suggestion.
https://github.com/webui-dev/webui/commit/68a5d48e87c4e2398f4a27ae12b20f1e616a66ab
