### ISSUE TITLE
Creating a Release in a GitHub Action

### ISSUE THREAD

**Issue by AlbertShown** [webui-dev/webui#134]
We solved the compression `zip`/`gz` script (https://github.com/webui-dev/webui/issues/120). And we agreed that we should remove the pre-built binaries from the repo.

Why not create a new workflow task that automatically runs when a merge is tagged with `release`, so this workflow will build, compress, generate and add a new release?

**Comment by hassandraga** [comment]
This is important feature to add. I already removed all the compiled objects from the repo.

**Comment by ttytm** [comment]
Good to see you back @hassandraga. I hope it's going well.

Yep, this one will have a leverage. Also, for all wrapper libraries. I started working in at #155 as part of it and it's nearly finished.
We merged #152 a bit prematurely - though it does no harm, since no releases are being made yet - but once the Makefile is out of the way we can update the steps in the CI and it's done.

**Comment by hassandraga** [comment]
Sounds good @ttytm

**Comment by ttytm** [comment]
To share a thing that might be relevant and that I didn't came to mention in #152.

The PR intentionally didn't added the version number for the file names.
E.g. if you look at the file names:
https://github.com/webui-dev/webui/releases/tag/2.3.0 (latest release)
https://github.com/ttytm/webui/releases/tag/v0.0.1-test (WIP release on fork)

Not adding an additional version number to the release files is common e.g.:
https://github.com/neovim/neovim/releases/tag/stable
https://github.com/kovidgoyal/kitty/releases/tag/v0.29.2

This makes it easier to deal with in scripts.

E.g. it would allow to use always use an url like `/releases/latest/download/windows-msvc-x64.zip` to download the latest release without the need for traditional queries or to update it for to version changes in the file name:
https://github.com/ttytm/webui/releases/latest/download/windows-msvc-x64.zip
To download a specified version number a tag would be specified in the url
https://github.com/ttytm/webui/releases/download/v0.0.1-test/windows-msvc-x64.zip

**Comment by hassandraga** [comment]
It's fine not to add the version number in the file names. We can simply add later a short description readme file in `dist` to show the current version number.

**Comment by ttytm** [comment]
It's the same for the architecture in the file names. 

Adding it to downloadable archives, but keeping the filename simple.

This would make:
`macos-clang-x64.tar.gz`
`macos-clang-arm64.tar.gz`
With the file name for the static library release:
`libwebui-2-static.a`
instead of `libwebui-2-static-x64.a`

Currently, keeping just the architecture in the filename
https://github.com/webui-dev/webui/blob/0d400644d13740990aeb9dc813655cd02d140be9/Makefile#L22
Since we still have the same file names per platform keeping it won't add a lot to make things more distingushable.

We could use the simple filenames to spare this would make things simpler internally, also when we extend the architecture support. In CI and Release creation and when downloading, the outputs would be still fully usable and distinguishable.

So the suggestion is to remove `x64` from the current outputs. Please let me know what you think on this

**Comment by hassandraga** [comment]
I agree with your suggestion because the end-user can still see the platform version in the archive name.

**Comment by ttytm** [comment]
#168 Added the release workflow.
