### ISSUE TITLE
NMAKE : fatal error U1077: 'cl /Zl /Fowebui.obj /c /EHsc "../../../src/webui.c" /I "../../../include" 1>NUL 2>&1' : return code '0x2'

### ISSUE THREAD

**Issue by aismann** [webui-dev/webui#141]
Any hints? use the latest version from now

```
C:\Users\...\webui\build\Windows\MSVC>nmake

Microsoft (R) Program Maintenance Utility Version 14.36.32537.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Build WebUI Library (MSVC Release Static)...
NMAKE : fatal error U1077: 'cl /Zl /Fowebui.obj /c /EHsc "../../../src/webui.c" /I "../../../include" 1>NUL 2>&1' : return code '0x2'
Stop.
```

**Comment by AlbertShown** [comment]
Thank you for reporting this @aismann, To see more details about the error, please remove `1>NUL 2>&1` from `build/Windows/MSVC/Makefile`. Then run `nmake` again.

If you want to build the stable release, please use [this one](https://github.com/webui-dev/webui/releases).

**Comment by tobealive** [comment]
I'm encountering a similar issue while working on #134. This is the output with `1>NUL 2>&1` removed:

```
Microsoft (R) Program Maintenance Utility Version 14.35.32217.1
Copyright (C) Microsoft Corporation.  All rights reserved.

Build WebUI Library (MSVC Release Static)...
Microsoft (R) C/C++ Optimizing Compiler Version 19.35.32217.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

civetweb.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.35.32217.1 for x64
webui.c
Copyright (C) Microsoft Corporation.  All rights reserved.

../../../src/webui.c(5144): warning C4477: 'sprintf' : format string '%zu' requires an argument of type 'unsigned __int64', but variadic argument 1 has type 'DWORD'
../../../src/webui.c(5144): note: consider using '%lu' in the format string
Microsoft (R) Library Manager Version 14.35.32217.1
Copyright (C) Microsoft Corporation.  All rights reserved.

Build WebUI Library (MSVC Release Dynamic)...
Microsoft (R) C/C++ Optimizing Compiler Version 19.35.32217.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

civetweb.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.35.32217.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

webui.c
../../../src/webui.c(5144): warning C4477: 'sprintf' : format string '%zu' requires an argument of type 'unsigned __int64', but variadic argument 1 has type 'DWORD'
../../../src/webui.c(5144): note: consider using '%lu' in the format string
/usr/bin/link: extra operand 'webui.obj'
Try '/usr/bin/link --help' for more information.
NMAKE : fatal error U1077: 'link /DLL /OUT:webui-2-x64.dll webui.obj civetweb.obj user32.lib Advapi32.lib' : return code '0x1'
Stop.
```

I'm coming across this error after finding out that our current MSVC CI action apparently doesn't do anything, it just goes green without actually running nmake. Which is probably due to: https://github.com/webui-dev/webui/blob/10e11da5e2f0dd2282662caa0eba531e8c2f4ec5/.github/workflows/build.yml#L26C11-L26C106 . The `.bat` file that is being called here isn't available at this path. Making nmake actually executable and then running it in `build/Windows/MSVC`, produces the error above in a github action. Testing on windows in a virtual machine I can successfully compile with nmake though.

I will dig a bit deeper later this day but maybe this is a first step coming closer to a solution.

**Comment by aismann** [comment]
`C:\Users\...\webui\build\Windows\MSVC>nmake

Microsoft (R) Program Maintenance Utility Version 14.36.32537.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Build WebUI Library (MSVC Release Static)...
Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32537 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

civetweb.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32537 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

webui.c
../../../src/webui.c(1915): error C2065: 'webui_javascript_bridge': undeclared identifier
../../../src/webui.c(1915): warning C4047: 'function': 'const char *' differs in levels of indirection from 'int'
../../../src/webui.c(1915): warning C4024: '_webui_strlen': different types for formal and actual parameter 1
../../../src/webui.c(1926): error C2065: 'webui_javascript_bridge': undeclared identifier
../../../src/webui.c(1925): warning C4477: 'sprintf' : format string '%s' requires an argument of type 'char *', but variadic argument 1 has type 'int'
NMAKE : fatal error U1077: 'cl /Zl /Fowebui.obj /c /EHsc "../../../src/webui.c" /I "../../../include"' : return code '0x2'
Stop.
`

**Comment by AlbertShown** [comment]
**Error:** `../../../src/webui.c(1915): error C2065: 'webui_javascript_bridge': undeclared identifier`

But the identifier `webui_javascript_bridge` is declared in line number 20.

https://github.com/webui-dev/webui/blob/4d76051471328f15a691c9ba0c9b540b4da99fc5/src/webui.c#L20

**Comment by AlbertShown** [comment]
@JOTSR How `client_webui_js` is provided?

**Comment by JOTSR** [comment]
I think that the error comes from xxd invocation. Have you pull the repo recently because I have made a [fix commit](https://github.com/webui-dev/webui/commit/068d99fa0420d38c1aba7f856185f73661e3bb0c) that solve a similar error.

Check that the build script you use invoke xxd as here: `xxd -i client/webui.js client/webui.h` (from `src/`)

Be aware that the path provided to xxd will define the variables names in the output `src/client/webui.h` and so can mismatch from webui.c declaration.

If the problem persists send the declarations in `src/client/webui.h`.

**Comment by AlbertShown** [comment]
@JOTSR, I guess we must try to make the build process easier, so the user simply does three steps, 1 install xxd, 2 install esbuild, and 3 run the build script.

Btw, How `client_webui_js` is provided?

**Comment by JOTSR** [comment]
There is an `#include "client/webui.h`.

**Comment by hassandraga** [comment]
Now we moved to `webui/bridge`. No need to re-build the webui-bridge.
Just clone, and build.
