### ISSUE TITLE
Linking with Musl

### ISSUE THREAD

**Issue by wwderw** [webui-dev/webui#260]
Strange thing is that I'm able to get the nim version to compile under musl just fine, but when I try to build it as a C project.  Everything compiles and I run ldd, it shows up as statically linked, but it tells me that the file/folder doesn't exist when I try to run it.  This is compiling the official 2.3 release.  Nightly doesn't seem to want to build regardless if I use musl or gcc (although in the past it has with gcc, so I figured something was going on with nightly)

Any thoughts as to what would be the best way to build for musl? 

Thanks for the help.

**Comment by ttytm** [comment]
Hey @wwderw 

to better help you, please provide info about the platform and compiler version you are using.

For building nightly did you clone the repo and try to build it as shown in the readme instructions?

**Comment by wwderw** [comment]
@ttytm 

GCC: 13.2.1
Musl: 1.2.4
OS: Arch-linux

Building Nightly with Regular GCC: Yes, I did follow the readme.  It had worked previously, just fine.  I did complain on it not being .git, which I thought was strange.

2.3 Build: Git clone worked, both doing regular make and doing CC=musl-gcc make (I made sure all intermediate and archive files were removed between build.  Regular build went fine.  It was only when changing CC to musl-gcc, it would build, but give the previous error msg.  I was expecting to get reference issues if I still was using the regular gcc built archive, but no errors like that, build my final binary just fine.

Setup works fine for the nim bindings.  Depending on what other libraries I want to use, I may switch between the two (still sometimes easier for me to default to C compared to nim).

**Comment by ttytm** [comment]
> Building Nightly with Regular GCC: Yes, I did follow the readme. It had worked previously, just fine. I did complain on it not being .git, which I thought was strange.

It's likely that you downloaded the source code from the releases and then tried to built it. GitHub won't add the `.git` repository to `Source code` releases that are automatically added when a release tag is created. They are stripped.

<img width="898" alt="Screenshot 2023-10-27 at 14 50 17" src="https://github.com/webui-dev/webui/assets/34311583/9368bfdd-a9c0-47f3-8fa1-a99c5656968d">

When a free moment opens up, I'll look into allowing building in the case someone made a Source code download via the releases. Though I'm not classifying it as high priority, since the releases are intended for the pre-built binaries and common way for developing and building is doing a `git clone` of the repository.

If you just want a quick copy of a single tag you do a shallow clone:
```sh
git clone --branch nightly --depth 1 https://github.com/webui-dev/webui webui-nightly
cd webui-nightly
make
```

> 2.3 Build: Git clone worked, both doing regular make and doing CC=musl-gcc make (I made sure all intermediate and archive files were removed between build. Regular build went fine. It was only when changing CC to musl-gcc, it would build, but give the previous error msg when I tried to run it, however it would still let me know that it was a static build. I was expecting to get reference issues if I still was using the regular gcc built archive, but no errors like that, built my final binary just fine.

Specifying custom compilers like `CC=musl-gcc` is not supported by WebUIs GNUMakefile. It's likely that just default `gcc` was used. If you want to use compilers that are not officially supported you either need to do run the full build commands yourself. Or in case of your `musl-gcc` making it available as `gcc` in your PATH. One way of solving it could be:

```sh
# Or whatever the path would be used for binaries on your system
ln -s path_to_musl_gcc/musl-gcc /usr/local/bin/gcc
```

**Comment by wwderw** [comment]
@ttytm 
When it complained it not having .git was when I download, but I have also done a git clone as well.  I did the git clone first and when that didn't work, I tried just downloading it.  But since I found out that the Makefile doesn't support a switch like that, it makes since that it didn't support it.

Would setting up musl as a gcc alias work?

**Comment by hassandraga** [comment]
`CC=musl-gcc` is now supported (https://github.com/webui-dev/webui/commit/30a1e49130a412e1ab59eda7ce3a005ad1984318).
Thank you @wwderw for pointing this out.

```
git clone --branch nightly --depth 1 https://github.com/webui-dev/webui webui-nightly

cd webui-nightly
make CC=musl-gcc

cd examples/C/text-editor
make CC=musl-gcc
```

**Comment by wwderw** [comment]
@hassandraga  @ttytm 

Success!!  Thank you both for the help.  I really do appreciate it.
